// AuthService unit tests — Phase C identity port (Remote-verified behavior).
// Unit-level evidence with the REAL crypto stack (VeloraHasher + JwtService)
// and an in-memory UserStore (the authorized local persistence boundary).
import { test } from "node:test";
import assert from "node:assert/strict";
import { AuthService, AuthError, ACCESS_TOKEN_TTL_SECONDS } from "./authService.js";
import { MemoryUserStore } from "./memoryUserStore.js";
import { VeloraHasher } from "./hashing.js";
import { JwtService } from "./jwt.js";
import { LogMailProvider } from "../mail/logMailProvider.js";

const SECRET = "auth-service-unit-test-secret-0123456789abcdef"; // 42 chars, test-only
const PHP_BCRYPT_2Y_COST10 =
  "$2y$10$.vGA1O9wmRjrwAVXD98HNOgsNpDczlqm3Jq7KnEd1rVAGv3Fykk1a"; // PHP manual vector
const VECTOR_PASSWORD = "rasmuslerdorf"; // public documentation example, not a credential

interface TestHarness {
  store: MemoryUserStore;
  service: AuthService;
  /** Raw verification tokens generated by THIS service instance (in order). */
  tokens: string[];
  /** Offline outbox — proves dispatch without any network or real key. */
  mail: LogMailProvider;
}

/**
 * COMPILE-TIME PROOF (C-41): email delivery cannot be silently disabled by
 * forgetting to wire the MailPort. `mail` is a REQUIRED member of AuthDeps, so
 * omitting it is a type error (TS2345/TS2741) — the build fails instead of
 * verification and password-reset links being minted and then dropped.
 *
 * If the dependency is ever made optional again, the `@ts-expect-error` below
 * becomes an UNUSED directive and `npm run typecheck` fails (TS2578). This
 * assertion is therefore self-policing in both directions.
 */
function _mailPortIsRequiredAtCompileTime(store: MemoryUserStore): void {
  // @ts-expect-error - mail is required; omitting it must not compile.
  void new AuthService({ store, hasher: new VeloraHasher(), jwt: JwtService.create(SECRET) });
}
void _mailPortIsRequiredAtCompileTime;

let tokenCounter = 0;

function makeService(overrides: { now?: () => Date } = {}): TestHarness {
  const store = new MemoryUserStore();
  const tokens: string[] = [];
  const mail = new LogMailProvider();
  const service = new AuthService({
    store,
    mail,
    hasher: new VeloraHasher(),
    // JwtService clock is unix SECONDS; the service clock is a Date.
    jwt: JwtService.create(SECRET, {
      now: () => Math.floor((overrides.now ?? (() => new Date()))().getTime() / 1000),
    }),
    ...(overrides.now ? { now: overrides.now } : {}),
    // deterministic verification tokens (test injection; production uses CSPRNG)
    generateVerificationToken: () => {
      const t = `deterministic-verification-token-${++tokenCounter}-0123456789abcdef`;
      tokens.push(t);
      return t;
    },
  });
  return { store, service, tokens, mail };
}

async function registerVerifiedUser(
  h: TestHarness,
  email = "user@velora.example",
  password = "a-strong-password-123",
): Promise<void> {
  await h.service.register({ email, password });
  const token = h.tokens.shift();
  assert.ok(token !== undefined, "verification token expected");
  await h.service.verifyEmail(token);
}

test("register: new user → {verificationRequired, email}, no messageKey", async () => {
  const h = makeService();
  const r = await h.service.register({ email: "new@velora.example", password: "a-strong-password-123" });
  assert.deepEqual(r, { verificationRequired: true, email: "new@velora.example" });
});

test("C-41 register: dispatches EXACTLY ONE verification email to the new user", async () => {
  const h = makeService();
  await h.service.register({ email: "dispatch@velora.example", password: "a-strong-password-123" });

  assert.equal(h.mail.outbox.length, 1, "registration must dispatch exactly one email");
  const msg = h.mail.lastTo("dispatch@velora.example");
  assert.ok(msg !== null, "the verification email must target the registered address");
  assert.equal(msg.subject, "Verify your VELORA TRADE email address");

  // The dispatched link must carry the SAME token the flow minted, and that
  // token must be the one the verification endpoint accepts.
  const token = h.tokens[0];
  assert.ok(token !== undefined);
  assert.ok(msg.text.includes(token), "the email must carry the minted verification token");
  await h.service.verifyEmail(token); // real endpoint accepts it → link is usable
});

test("C-41 register: the raw token is persisted only as a hash and never returned", async () => {
  const h = makeService();
  const res = await h.service.register({ email: "nosecret@velora.example", password: "a-strong-password-123" });
  const token = h.tokens[0]!;

  // API response must not carry the token.
  assert.equal(JSON.stringify(res).includes(token), false, "API response must not expose the token");

  // Storage must hold the sha256 hash, never the raw value.
  const user = await h.store.findUserByEmail("nosecret@velora.example");
  const latest = await h.store.latestVerification(user!.id);
  assert.ok(latest !== null);
  assert.equal(latest.tokenHash.includes(token), false, "raw token must never be stored");
  assert.equal(latest.tokenHash.length, 64, "verification token is stored as a sha256 hex digest");
});

test("C-41 register: a mail provider FAILURE never changes the registration outcome", async () => {
  // Delivery is fail-safe by design: a throwing adapter must not surface
  // provider state, fail the request, or roll back the created account.
  const store = new MemoryUserStore();
  const throwing = {
    name: "throwing",
    send: async (): Promise<never> => {
      throw new Error("provider exploded");
    },
  };
  const svc = new AuthService({
    store,
    hasher: new VeloraHasher(),
    jwt: JwtService.create(SECRET),
    mail: throwing,
  });

  const r = await svc.register({ email: "boom@velora.example", password: "a-strong-password-123" });
  assert.deepEqual(r, { verificationRequired: true, email: "boom@velora.example" });
  assert.ok((await store.findUserByEmail("boom@velora.example")) !== null, "account still created");
});

test("C-41 resend: re-registering an unverified user dispatches another email", async () => {
  const h = makeService({ now: () => new Date("2026-01-01T00:00:00.000Z") });
  await h.service.register({ email: "again@velora.example", password: "a-strong-password-123" });
  assert.equal(h.mail.outbox.length, 1);

  // Second attempt after the retry interval — existing rate-limit semantics
  // are unchanged; this only proves the dispatch still happens.
  const later = makeService({ now: () => new Date("2026-01-01T00:05:00.000Z") });
  await later.service.register({ email: "again2@velora.example", password: "a-strong-password-123" });
  assert.equal(later.mail.outbox.length, 1, "resend path dispatches through the same port");
});

test("register: duplicate VERIFIED email → 409 EMAIL_ALREADY_REGISTERED", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "dupe@velora.example");
  await assert.rejects(
    h.service.register({ email: "DUPE@velora.example", password: "another-strong-pass-456" }),
    (e: unknown) => e instanceof AuthError && e.status === 409 && e.code === "EMAIL_ALREADY_REGISTERED",
  );
});

test("register: unverified re-register → 60s retry delay, then resend path (reference semantics)", async () => {
  // NOTE (evidence-based Remote quirk, documented): the reference deletes prior
  // verification rows before creating a new one, so at most ONE row per user
  // exists when the 3-per-24h count runs — VERIFICATION_LIMIT is unreachable
  // in the reference and therefore also here (ported faithfully; flagged for
  // owner review when the Phase I email waves revisit resend limits).
  let clock = new Date("2026-09-12T10:00:00Z");
  const h = makeService({ now: () => clock });
  await h.service.register({ email: "unverified@velora.example", password: "a-strong-password-123" });

  clock = new Date("2026-09-12T10:00:30Z"); // within 60s → retry delay
  await assert.rejects(
    h.service.register({ email: "unverified@velora.example", password: "a-strong-password-123" }),
    (e: unknown) => e instanceof AuthError && e.code === "VERIFICATION_RETRY_DELAY",
  );

  clock = new Date("2026-09-12T10:02:00Z"); // after the interval → resend
  const r = await h.service.register({ email: "unverified@velora.example", password: "a-strong-password-123" });
  assert.equal(r.messageKey, "auth.verificationResent");
  assert.equal(r.verificationRequired, true);
});

test("verifyEmail: valid token verifies; replay → alreadyVerified; bad/expired → 401 INVALID_TOKEN", async () => {
  let clock = new Date("2026-09-12T10:00:00Z");
  const h = makeService({ now: () => clock });
  await h.service.register({ email: "verify@velora.example", password: "a-strong-password-123" });
  const token = h.tokens.shift();

  const first = await h.service.verifyEmail(token!);
  assert.equal(first.alreadyVerified, false);
  assert.equal(first.messageKey, "auth.emailVerified");

  const replay = await h.service.verifyEmail(token!);
  assert.equal(replay.alreadyVerified, true);
  assert.equal(replay.messageKey, "auth.emailAlreadyVerified");

  await assert.rejects(
    h.service.verifyEmail("not-a-real-token-0123456789abcdef"),
    (e: unknown) => e instanceof AuthError && e.status === 401 && e.code === "INVALID_TOKEN",
  );

  await h.service.register({ email: "expired@velora.example", password: "a-strong-password-123" });
  const expiredToken = h.tokens.shift();
  clock = new Date("2026-09-14T10:00:00Z"); // beyond the 24h expiry
  await assert.rejects(
    h.service.verifyEmail(expiredToken!),
    (e: unknown) => e instanceof AuthError && e.code === "INVALID_TOKEN",
  );
});

test("login: failure order — credentials, then status, then verification", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "active@velora.example", "right-password-123");

  await assert.rejects(
    h.service.login({ email: "active@velora.example", password: "wrong-password-999" }),
    (e: unknown) => e instanceof AuthError && e.status === 401 && e.code === "INVALID_CREDENTIALS",
  );
  await assert.rejects(
    h.service.login({ email: "ghost@velora.example", password: "whatever-password-1" }),
    (e: unknown) => e instanceof AuthError && e.code === "INVALID_CREDENTIALS",
  );

  await registerVerifiedUser(h, "inactive@velora.example", "right-password-123");
  const inactive = await h.store.findUserByEmail("inactive@velora.example");
  assert.ok(inactive !== null);
  (inactive as { status: string }).status = "suspended";
  await assert.rejects(
    h.service.login({ email: "inactive@velora.example", password: "right-password-123" }),
    (e: unknown) => e instanceof AuthError && e.code === "ACCOUNT_INACTIVE",
  );
});

test("login: UNVERIFIED email → 401 EMAIL_NOT_VERIFIED", async () => {
  const h = makeService();
  await h.service.register({ email: "unv@velora.example", password: "a-strong-password-123" });
  await assert.rejects(
    h.service.login({ email: "unv@velora.example", password: "a-strong-password-123" }),
    (e: unknown) => e instanceof AuthError && e.code === "EMAIL_NOT_VERIFIED",
  );
});

test("login: legacy $2y$ verifies AND rehashes to exact Argon2id through the store (S5 boundary)", async () => {
  const h = makeService();
  const legacy = await h.store.createUser({
    email: "legacy@velora.example",
    passwordHash: PHP_BCRYPT_2Y_COST10,
    fullName: "Legacy User",
    timezone: "UTC",
    locale: "fa",
    now: new Date("2026-09-12T09:00:00Z"),
  });
  await h.store.markEmailVerified(legacy.id, new Date("2026-09-12T09:01:00Z"));

  const pair = await h.service.login({ email: "legacy@velora.example", password: VECTOR_PASSWORD });
  assert.equal(pair.tokenType, "Bearer");
  assert.equal(pair.expiresIn, ACCESS_TOKEN_TTL_SECONDS);
  assert.equal(pair.user.email, "legacy@velora.example");
  assert.equal(pair.user.plan, "free");

  const stored = await h.store.findUserByEmail("legacy@velora.example");
  assert.ok(stored!.passwordHash.startsWith("$argon2id$v=19$m=19456,t=2,p=1$"), "rehash persisted");

  const payload = h.service.verifyAccessToken(pair.accessToken);
  assert.equal(payload?.sub, legacy.id);
  assert.equal(payload?.role, "user");

  const second = await h.service.login({ email: "legacy@velora.example", password: VECTOR_PASSWORD });
  assert.ok(second.accessToken.length > 0);
  const storedAfter = await h.store.findUserByEmail("legacy@velora.example");
  assert.equal(storedAfter!.passwordHash, stored!.passwordHash, "no unnecessary rehash");
});

test("login: compliant Argon2id user — no unnecessary rehash", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "modern@velora.example", "compliant-password-42");
  const before = (await h.store.findUserByEmail("modern@velora.example"))!.passwordHash;
  await h.service.login({ email: "modern@velora.example", password: "compliant-password-42" });
  const after = (await h.store.findUserByEmail("modern@velora.example"))!.passwordHash;
  assert.equal(after, before);
});

test("refresh: rotates the session; old token dies, new one works", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "refresh@velora.example", "a-strong-password-123");
  const pair = await h.service.login({ email: "refresh@velora.example", password: "a-strong-password-123" });

  const rotated = await h.service.refresh(pair.refreshToken);
  assert.notEqual(rotated.refreshToken, pair.refreshToken);
  assert.notEqual(rotated.accessToken, pair.accessToken);

  await assert.rejects(
    h.service.refresh(pair.refreshToken),
    (e: unknown) => e instanceof AuthError && e.code === "INVALID_TOKEN",
  );
  const again = await h.service.refresh(rotated.refreshToken);
  assert.ok(again.refreshToken.length > 0);
});

test("refresh: expired session → SESSION_EXPIRED", async () => {
  let clock = new Date("2026-09-12T10:00:00Z");
  const h = makeService({ now: () => clock });
  await registerVerifiedUser(h, "exp@velora.example", "a-strong-password-123");
  const pair = await h.service.login({ email: "exp@velora.example", password: "a-strong-password-123" });
  clock = new Date("2026-11-01T10:00:00Z"); // > 30 days
  await assert.rejects(
    h.service.refresh(pair.refreshToken),
    (e: unknown) => e instanceof AuthError && e.code === "SESSION_EXPIRED",
  );
});

test("logout: revokes the session (idempotent); refresh after logout → INVALID_TOKEN", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "out@velora.example", "a-strong-password-123");
  const pair = await h.service.login({ email: "out@velora.example", password: "a-strong-password-123" });
  await h.service.logout(pair.refreshToken);
  await h.service.logout(pair.refreshToken); // idempotent
  await assert.rejects(
    h.service.refresh(pair.refreshToken),
    (e: unknown) => e instanceof AuthError && e.code === "INVALID_TOKEN",
  );
});

test("me: returns the Remote-verified PublicUserDto shape", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "me@velora.example", "a-strong-password-123");
  const user = await h.store.findUserByEmail("me@velora.example");
  const dto = await h.service.me(user!.id);
  assert.deepEqual(Object.keys(dto).sort(), [
    "aiConsent",
    "createdAt",
    "email",
    "fullName",
    "id",
    "locale",
    "plan",
    "role",
    "timezone",
  ]);
  assert.equal(dto.plan, "free");
  assert.equal(dto.timezone, "UTC");
  assert.equal(dto.locale, "fa");
  assert.equal(dto.aiConsent, false);
  assert.equal(typeof dto.id, "number");
});

test("changePassword: policy + revocation semantics (service level)", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "policy@velora.example", "original-password-123");
  const userId = (await h.store.findUserByEmail("policy@velora.example"))!.id;
  const pair = await h.service.login({ email: "policy@velora.example", password: "original-password-123" });

  // weak new password → VALIDATION_FAILED on newPassword (Local policy min 10; PHP min 8 — documented difference)
  await assert.rejects(
    h.service.changePassword(userId, { currentPassword: "original-password-123", newPassword: "short" }),
    (e: unknown) => e instanceof AuthError && e.code === "VALIDATION_FAILED" && e.details?.newPassword !== undefined,
  );
  // missing user → USER_NOT_FOUND (ownership boundary)
  await assert.rejects(
    h.service.changePassword("999999", { currentPassword: "x", newPassword: "y-strong-enough-1" }),
    (e: unknown) => e instanceof AuthError && e.code === "USER_NOT_FOUND",
  );

  await h.service.changePassword(userId, { currentPassword: "original-password-123", newPassword: "rotated-password-456" });
  // every session of the user is revoked
  await assert.rejects(h.service.refresh(pair.refreshToken));
  // new password verifies; old one does not
  await assert.rejects(h.service.login({ email: "policy@velora.example", password: "original-password-123" }));
  await h.service.login({ email: "policy@velora.example", password: "rotated-password-456" });
});

test("preferences + email preferences service contracts", async () => {
  const h = makeService();
  await registerVerifiedUser(h, "svc-pref@velora.example", "a-strong-password-123");
  const userId = (await h.store.findUserByEmail("svc-pref@velora.example"))!.id;

  // no field → 400
  await assert.rejects(
    h.service.updatePreferences(userId, {}),
    (e: unknown) => e instanceof AuthError && e.code === "VALIDATION_FAILED",
  );
  const r = await h.service.updatePreferences(userId, { locale: "en", ai_consent: true });
  assert.deepEqual(
    { updated: r.updated, locale: r.locale, ai_consent: r.ai_consent },
    { updated: true, locale: "en", ai_consent: true },
  );

  const prefs = await h.service.getEmailPreferences(userId);
  assert.deepEqual(prefs.preferences, {
    welcome_email: 1, security_alerts: 1, trade_notifications: 1,
    weekly_report: 1, monthly_report: 1, achievement_notifications: 1,
  });
  const merged = await h.service.updateEmailPreferences(userId, { trade_notifications: false });
  assert.equal(merged.preferences.trade_notifications, 0);
  assert.equal(merged.preferences.weekly_report, 1); // no reset
});
