// Blog content data — AC-32 (MG-FRONTEND-SURFACES + MG-I18N-COVERAGE).
//
// PROVENANCE: the ordered message keys below are the `data-i18n` sequence of
// Legacy's own blog pages (veloratrade/veloratrade @edede31
// `blog/<slug>/index.html`), de-duplicated, with the page CHROME keys (brand,
// login, footer) removed — those belong to the shell, not the article. The
// strings themselves live in the `blog` + `common` catalogs (byte copies of
// Legacy's chunks + the 106 keys lifted from Legacy's canonical
// public/locales/{fa,en}.json). Nothing here is authored content: it is the
// article STRUCTURE Legacy shipped, rendered by Modern components.

export interface BlogPost {
  readonly slug: string;
  readonly titleKey: string;
  readonly keys: readonly string[];
}

export const BLOG_POSTS: readonly BlogPost[] = [
  { slug: "forex-trading-journal", titleKey: "pages.blog.forex_trading_journal.forex.trading.journal.the.best.way.to.85fd3338", keys: [
    "pages.blog.forex_trading_journal.forex.trading.journal.the.best.way.to.85fd3338",
    "common.home.ce76258c",
    "common.forex.trading.journal.how.to.track.and.b2b2e253",
    "common.forex.is.the.largest.financial.market.in.66d2be70",
    "common.forex.ed552007",
    "common.trading.journal.c6cb0c73",
    "common.market.analysis.e005b4c7",
    "common.8.min.read.81675063",
    "common.why.forex.needs.a.dedicated.journal.e339dfbb",
    "common.the.forex.market.operates.24.hours.a.a1751a7c",
    "common.forex.traders.typically.execute.many.trades.per.dd24696f",
    "common.forex.specific.journal.fields.ff184210",
    "common.beyond.general.fields.a.forex.journal.should.de4f9106",
    "common.recording.the.trading.session.is.crucial.many.7784fa5d",
    "common.performance.analysis.in.forex.91f58f9e",
    "common.with.a.forex.journal.you.can.compare.138b8815",
    "common.this.analysis.shows.whether.you.should.focus.c9ef0bf1",
    "common.key.insight.86760c1e",
    "pages.blog.forex_trading_journal.did.you.know.traders.who.record.their.742e5ad7",
    "common.frequently.asked.questions.20bafe39",
    "common.which.currency.pair.is.best.for.journaling.d3597472",
    "common.every.pair.you.trade.should.be.recorded.79aff7ef",
    "common.should.i.record.losing.trades.too.0e62a99c",
    "common.yes.recording.losing.trades.is.even.more.fb9c6aa3",
    "common.start.your.trading.journal.with.velora.d8e40af6",
    "common.track.your.trades.review.your.performance.and.f796c983",
    "common.create.free.account.e2f0847d",
    "common.related.articles.8a91dabb",
    "common.blog.2aa4a2af",
    "common.view.all.articles.1aea15fe",
    "common.create.your.trading.journal.5d0645f0",
    "common.home.e5608ccf",
    "common.privacy.3f5d8744",
    "common.terms.3a93abb8"
  ] },
  { slug: "mt4-mt5-trading-journal", titleKey: "pages.blog.mt4_mt5_trading_journal.connect.mt4.and.mt5.to.a.trading.67700f3f", keys: [
    "pages.blog.mt4_mt5_trading_journal.connect.mt4.and.mt5.to.a.trading.67700f3f",
    "common.home.ce76258c",
    "common.mt4.and.mt5.trading.journal.how.to.d8dc4ef2",
    "common.by.connecting.mt4.and.mt5.to.a.7ee69236",
    "common.metaapi.9974cbe0",
    "common.8.min.read.81675063",
    "common.why.mt4.mt5.connection.matters.6183ae57",
    "common.manual.trade.recording.is.tedious.and.error.626ca10a",
    "common.with.metaapi.you.can.connect.without.installing.00a8f22a",
    "common.security.of.mt4.mt5.connection.914c4ae2",
    "common.the.investor.password.has.read.only.access.d022cd15",
    "common.velora.uses.metaapi.for.secure.connection.and.f3ea0c21",
    "common.key.insight.86760c1e",
    "common.security.the.investor.password.is.read.only.661f32e0",
    "common.frequently.asked.questions.20bafe39",
    "common.do.i.need.to.install.an.ea.28323696",
    "common.no.with.metaapi.you.only.need.your.343a7c4f",
    "common.is.the.connection.secure.a74e99a7",
    "common.yes.the.investor.password.is.read.only.a1ae3100",
    "common.start.your.trading.journal.with.velora.d8e40af6",
    "common.track.your.trades.review.your.performance.and.f796c983",
    "common.create.free.account.e2f0847d",
    "common.related.articles.8a91dabb",
    "common.blog.2aa4a2af",
    "common.view.all.articles.1aea15fe",
    "common.create.your.trading.journal.5d0645f0",
    "common.home.e5608ccf",
    "common.privacy.3f5d8744",
    "common.terms.3a93abb8"
  ] },
  { slug: "risk-management-trading", titleKey: "pages.blog.risk_management_trading.what.is.risk.management.in.trading.a.4968c44b", keys: [
    "pages.blog.risk_management_trading.what.is.risk.management.in.trading.a.4968c44b",
    "common.home.ce76258c",
    "common.risk.management.in.trading.how.to.control.6e98ea9b",
    "common.risk.management.in.trading.means.controlling.position.a0c75ea0",
    "common.risk.management.4fd07387",
    "common.risk.management.fff835f0",
    "common.profit.factor.4f05d40f",
    "common.8.min.read.81675063",
    "common.finding.high.risk.patterns.e86d778b",
    "common.your.journal.may.show.that.certain.symbols.56176154",
    "pages.blog.risk_management_trading.core.principle.never.risk.more.than.1.474152de",
    "pages.blog.risk_management_trading.final.thoughts.871b6e7a",
    "common.risk.management.is.not.just.a.calculation.3346d5af",
    "pages.blog.risk_management_trading.risk.to.reward.ratio.at.least.1.28b770d5",
    "pages.blog.risk_management_trading.profit.factor.is.gross.profit.divided.by.d1a95372",
    "common.key.insight.86760c1e",
    "pages.blog.risk_management_trading.golden.rule.never.risk.more.than.2.c5da41e9",
    "common.frequently.asked.questions.20bafe39",
    "common.what.is.a.common.risk.per.trade.1d5eb854",
    "common.many.traders.use.0.5.to.2.429739ea",
    "common.is.risk.to.reward.always.more.important.ebe43434",
    "common.they.must.be.reviewed.together.a.low.4b8556e2",
    "common.start.your.trading.journal.with.velora.d8e40af6",
    "common.track.your.trades.review.your.performance.and.f796c983",
    "common.create.free.account.e2f0847d",
    "common.related.articles.8a91dabb",
    "common.blog.2aa4a2af",
    "common.view.all.articles.1aea15fe",
    "common.create.your.trading.journal.5d0645f0",
    "common.home.e5608ccf",
    "common.privacy.3f5d8744",
    "common.terms.3a93abb8"
  ] },
  { slug: "what-is-trading-journal", titleKey: "common.what.is.a.trading.journal.and.why.f4d13ce3", keys: [
    "common.what.is.a.trading.journal.and.why.f4d13ce3",
    "common.home.ce76258c",
    "common.what.is.a.trading.journal.a.complete.a1b35742",
    "common.a.trading.journal.is.not.just.a.d4d9db5d",
    "common.trading.journal.c6cb0c73",
    "common.risk.management.4fd07387",
    "common.analytics.da272333",
    "common.8.min.read.81675063",
    "common.what.should.you.record.in.a.trading.149cb707",
    "common.at.minimum.record.the.market.symbol.direction.5d39d843",
    "pages.blog.what_is_trading_journal.the.main.difference.between.successful.and.unsuccessful.25e8e63c",
    "common.why.does.journaling.improve.trading.performance.6b09ad4e",
    "common.improvement.requires.feedback.without.data.traders.often.9dfba46d",
    "pages.blog.what_is_trading_journal.if.you.record.only.profit.and.loss.1b6c633b",
    "common.key.insight.86760c1e",
    "pages.blog.what_is_trading_journal.key.point.every.trade.should.include.at.67f4565f",
    "common.manual.journal.vs.ai.trading.journal.96e2b3b0",
    "common.a.manual.journal.is.useful.for.beginners.ea5664e0",
    "pages.blog.what_is_trading_journal.a.journal.also.helps.identify.destructive.patterns.826f40d9",
    "common.final.thoughts.4bd8a554",
    "common.if.you.want.to.trade.professionally.journaling.2a37568e",
    "pages.blog.what_is_trading_journal.a.smart.journal.such.as.velora.automatically.ac474e1f",
    "common.frequently.asked.questions.20bafe39",
    "common.is.a.trading.journal.only.for.forex.c0f24237",
    "common.no.it.works.for.forex.crypto.cfds.c58c7870",
    "common.how.often.should.i.update.my.journal.83f88df2",
    "common.ideally.after.every.trade.or.at.the.30b3d2da",
    "common.can.an.ai.journal.replace.self.review.cf62be48",
    "common.no.it.improves.the.review.process.but.256cf1d8",
    "common.start.your.trading.journal.with.velora.d8e40af6",
    "common.track.your.trades.review.your.performance.and.f796c983",
    "common.create.free.account.e2f0847d",
    "common.related.articles.8a91dabb",
    "common.blog.2aa4a2af",
    "common.view.all.articles.1aea15fe",
    "common.create.your.trading.journal.5d0645f0",
    "common.home.e5608ccf",
    "common.privacy.3f5d8744",
    "common.terms.3a93abb8"
  ] },
  { slug: "why-traders-need-journal", titleKey: "pages.blog.why_traders_need_journal.why.do.traders.need.a.trading.journal.37eb5f5c", keys: [
    "pages.blog.why_traders_need_journal.why.do.traders.need.a.trading.journal.37eb5f5c",
    "common.home.ce76258c",
    "common.why.traders.need.a.journal.the.mistakes.7d1efd74",
    "common.traders.repeat.mistakes.when.they.do.not.c3454f20",
    "common.psychology.5aff3cdc",
    "common.trading.journal.c6cb0c73",
    "common.performance.analytics.e111be03",
    "common.8.min.read.81675063",
    "common.improvement.requires.evidence.19112c24",
    "common.if.the.data.shows.most.of.your.3596b949",
    "pages.blog.why_traders_need_journal.studies.show.that.after.two.years.80.492f1b79",
    "pages.blog.why_traders_need_journal.final.thoughts.ec569242",
    "common.trading.without.a.journal.is.like.training.31366130",
    "pages.blog.why_traders_need_journal.mistake.two.overtrading.without.recording.your.daily.db7b82cd",
    "pages.blog.why_traders_need_journal.mistake.three.breaking.your.plan.a.positive.93114a02",
    "common.key.insight.86760c1e",
    "pages.blog.why_traders_need_journal.the.hard.truth.90.of.traders.without.af51a569",
    "common.frequently.asked.questions.20bafe39",
    "common.do.beginner.traders.need.a.journal.8ef4eb81",
    "common.yes.journaling.early.helps.build.strong.habits.db374e8e",
    "common.how.does.a.journal.help.with.emotions.3cf03112",
    "common.it.turns.emotions.into.observable.patterns.such.e1963863",
    "common.start.your.trading.journal.with.velora.d8e40af6",
    "common.track.your.trades.review.your.performance.and.f796c983",
    "common.create.free.account.e2f0847d",
    "common.related.articles.8a91dabb",
    "common.blog.2aa4a2af",
    "common.view.all.articles.1aea15fe",
    "common.create.your.trading.journal.5d0645f0",
    "common.home.e5608ccf",
    "common.privacy.3f5d8744",
    "common.terms.3a93abb8"
  ] },
];

/** Ordered keys of the blog index page's own content (hero + article cards). */
export const BLOG_INDEX_KEYS: readonly string[] = [
  "pages.blog.velora.blog.trading.journal.and.risk.management.68b13dc3",
  "common.velora.2e043621",
  "common.login.e09e596b",
  "common.start.free.7af5f589",
  "common.professional.trading.education.9ae5f789",
  "common.blog.4a829cc7",
  "common.education.for.trading.journals.performance.analytics.risk.75b21185",
  "common.articles.99a75fcc",
  "common.categories.33be46a3",
  "common.free.3d88da0e",
  "common.editor.s.picks.a78b2c29",
  "common.featured.8dea656a",
  "common.what.is.a.trading.journal.a.complete.a239bd98",
  "pages.blog.a.trading.journal.helps.traders.track.decisions.e11ee3a4",
  "common.8.min.read.81675063",
  "common.beginner.to.advanced.99630cc4",
  "common.risk.management.4fd07387",
  "common.risk.management.in.trading.how.to.control.6e98ea9b",
  "common.risk.management.means.controlling.position.size.stop.6056da66",
  "pages.blog.10.min.read.f7b8245f",
  "common.intermediate.to.advanced.2a149d9f",
  "common.all.articles.5a07294c",
  "common.forex.ed552007",
  "common.forex.trading.journal.how.to.track.and.b2b2e253",
  "common.learn.how.a.forex.trading.journal.helps.61666b3e",
  "pages.blog.7.min.read.101a3700",
  "common.psychology.5aff3cdc",
  "pages.blog.why.traders.need.a.journal.the.mistakes.2e7337df",
  "pages.blog.traders.repeat.mistakes.when.they.do.not.21bc5e3c",
  "pages.blog.6.min.read.0024cd2e",
  "common.beginner.fcb2f577",
  "pages.blog.mt4.and.mt5.trading.journal.how.to.50dbbf4c",
  "common.learn.how.connecting.mt4.and.mt5.to.ed619909",
  "pages.blog.9.min.read.a3b8510d",
  "common.technical.28677e76",
  "common.analytics.da272333",
  "common.trading.performance.analytics.key.metrics.every.trader.4d29cafb",
  "common.win.rate.profit.factor.drawdown.and.r.5ad71c8f",
  "common.intermediate.48615c71",
  "common.stay.updated.with.new.articles.86805643",
  "common.get.the.latest.velora.educational.articles.delivered.ffc7dade",
  "common.subscribe.8b94a86e",
  "common.subscribed.you.ll.be.the.first.to.1d9ddce2",
  "pages.blog.2026.velora.all.rights.reserved.888bbd54",
  "common.home.e5608ccf",
  "common.privacy.3f5d8744",
  "common.terms.3a93abb8"
];
